<a href="https://colab.research.google.com/github/Bart-del/studies-machine-learning/blob/main/Zadanie_1_5_B_Wysocki.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**<h1>Zadanie 1.5**

>Czym różni się operacja `A**-1` dla obiektów typu `array` i `matrix`? Pokaż na przykładzie.

Zarówno dla obiektu typu array oraz matrix operacja A**-1 oznacza tzw. inwersję.
Przebiega ona inaczej dla tych obiektów.




In [6]:
import numpy as np
A = np.array([[1,2,1],[0,2,1],[3,6,1]])

print(np.linalg.inv(A))
print('--------')
print(np.linalg.inv(A.T))

[[ 1.00000000e+00 -1.00000000e+00  1.11022302e-16]
 [-7.50000000e-01  5.00000000e-01  2.50000000e-01]
 [ 1.50000000e+00  0.00000000e+00 -5.00000000e-01]]
--------
[[ 1.   -0.75  1.5 ]
 [-1.    0.5  -0.  ]
 [-0.    0.25 -0.5 ]]
